include:
  - component: git.apsolutions.ru/aps/Internal/streaming-platform/common/ci-components/image-build@0.8.3
    inputs:
      dockerfile: ./Dockerfile
      image_name: $HARBOR_URL/research/country/frontend
      stage: build
      job_name: frontend
      autobuild_branches: true
      only_on_tag: false

stages:
  - build
