apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: country-frontend
spec:
  rules:
    - host: country.aps
      http:
        paths:
          - backend:
              service:
                name: country-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: country-frontend-public
spec:
  rules:
    - host: country.apsolutions.ru
      http:
        paths:
          - backend:
              service:
                name: country-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
