apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-rag-frontend
spec:
  rules:
    - host: graph-rag.aps
      http:
        paths:
          - backend:
              service:
                name: graph-rag-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-rag-frontend-public
spec:
  rules:
    - host: graph-rag.apsolutions.ru
      http:
        paths:
          - backend:
              service:
                name: graph-rag-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
