apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    app.kubernetes.io/name: graph-rag-frontend
    app.kubernetes.io/instance: graph-rag-frontend

resources:
  - frontend
  - ./ingress.yaml
