apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
    app.kubernetes.io/name: country-frontend
    app.kubernetes.io/instance: country-frontend

resources:
  - frontend
  - ./ingress.yaml
