apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - image: harbor.apsolutions.ru/research/graph-rag-frontend:debug
          imagePullPolicy: IfNotPresent
          name: country-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          resources: 
            requests:
              cpu: 100m
              memory: 50Mi
      imagePullSecrets:
        - name: harborcred
      terminationGracePeriodSeconds: 30
