apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-frontend
  template:
    metadata:
      labels:
        app: country-frontend
    spec:
      containers:
        - image: harbor.apsolutions.ru/research/country/frontend:debug
          imagePullPolicy: IfNotPresent
          name: country-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harborcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
